package com.shreebenakaspace.repository;

import com.shreebenakaspace.model.Song;
import org.springframework.data.jpa.repository.JpaRepository;

import java.util.List;

public interface SongRepositoryInterface extends JpaRepository<Song, Integer> {
    // 🔍 Custom query (auto-generated by Spring)
    List<Song> findBySingerIgnoreCase(String singer);

    List<Song> findByCategoryIgnoreCase(String category);

}
